### ISSUE TITLE
问个kotlin上传jCenter的问题

### ISSUE THREAD

**Issue by vihuela** [fengzhizi715/SAF-Kotlin-log#2]
我在[bintray-release issue#130](https://github.com/novoda/bintray-release/issues/130)留言，作者说不支持kotlin上传，但是你是怎么上传的？我上传，老是提示： Could not find publication: release.

**Comment by fengzhizi715** [comment]
hi @vihuela  我上传了好几个lib，是可以上传的。
在root目录下的build.gradle中将classpath 'com.novoda:bintray-release:+'改成
classpath 'com.novoda:bintray-release:0.4.0' 试试

**Comment by vihuela** [comment]
谢谢哥们回复，@fengzhizi715 ，tasks.getByPath(":saf-log:releaseAndroidJavadocs").enabled = false
是怎么添加的？我跑起来说没有这个task

**Comment by fengzhizi715** [comment]
@vihuela 这个task是我这个库里的，你肯定没有啦。主要是忽略javadoc的任务，你可以注释掉。
如果你也遇到同样的问题，将saf-log替换成你项目中module的名称。

**Comment by vihuela** [comment]
@fengzhizi715 有替换成我项目中的，还是提示task未存在。。。。不过现在是一直是，执行上传命令：
就显示：Could not find publication: release.，我clone下你的项目，搞不懂了。。。。方便留下qq或者微信么，我要是再搞不定，问你。。

**Comment by fengzhizi715** [comment]
@vihuela 我的微信：fengzhizi715
