### ISSUE TITLE
Log debug开关

### ISSUE THREAD

**Issue by aiLvXuan** [fengzhizi715/SAF-Kotlin-log#4]
在正式打包发布时，可以一键关闭Log的输出吗？

**Comment by fengzhizi715** [comment]
hi @aiLvXuan  可以在Application中设置logLevel，默认是DEBUG
在开发时使用d(), 等打包时改成INFO

**Comment by aiLvXuan** [comment]
@fengzhizi715 

> 可以在Application中设置logLevel，默认是DEBUG 在开发时使用d(), 等打包时改成INFO

了解。但是使用L.json( ) 打印，没有《RxJava2.x 实战》中的好看，买家秀和买家秀，哈哈。
![img_20180720_162451](https://user-images.githubusercontent.com/22241686/42993826-fc460b5c-8c3e-11e8-927f-0514d8ca2d85.jpg)
![uc 20180720165238](https://user-images.githubusercontent.com/22241686/42993848-0caf3874-8c3f-11e8-8690-48f933c3d247.png)

**Comment by fengzhizi715** [comment]
@aiLvXuan  书里网络请求用的日志框架是这个：https://github.com/fengzhizi715/saf-logginginterceptor
它是OKHttp的日志的拦截器

**Comment by fengzhizi715** [comment]
谢谢购买我的书，有问题随时联系我 ：）

**Comment by aiLvXuan** [comment]
@fengzhizi715 好的，谢谢
